"""Validate the synthetic data generated by attrition_extension.py and
spend_generator.py against their own documented target parameters, and
run a generation-parameter perturbation sensitivity check.

Produces data/generated/validation_report.md.

Scope note on the perturbation check: this script perturbs *generation*
parameters (lambda, lognormal mu/sigma, raise-percent mean, hot-employee
concentration) by +/-20% and confirms the resulting *data-level* summary
statistics (category amount distributions, anomaly-type mix, base rates)
stay qualitatively stable. It does not re-run the full attrition/spend
model-training pipelines (Sections 5-6), since those don't exist yet at
the point this script runs in the build order. The model-level robustness
check the build spec also asks for — whether precision/recall/PR-AUC hold
up under a changed generation parameter — is the injection-rate robustness
comparison in src/models/spend/evaluate.py (1%/5%/10% variants), which is
the actual eval-metric-level version of this same question.
"""

import os

import numpy as np
import pandas as pd
from scipy import stats as sps

from src.generation.spend_generator import (
    CATEGORY_LOGNORMAL_PARAMS,
    DEPARTMENT_LAMBDA,
    HOT_EMPLOYEE_FRACTION,
    HOT_ANOMALY_SHARE,
    generate_all as generate_spend_all,
    generate_base_transactions,
    inject_anomalies,
)

DIST_FLAG_THRESHOLD = 0.15
CORR_FLAG_THRESHOLD = 0.30
# "Still too coarse" flag threshold for distinct duration_months values. Roughly
# half of 1,470 employees / 12 months-per-year = ~61, i.e. the number you'd expect
# if durations spread only about half as evenly as a full independent-per-month
# distribution would give across a realistic tenure range — a conservative floor
# for "meaningfully more resolution than the annual-only original", not a claim
# about any theoretically ideal count.
MIN_DISTINCT_DURATION_MONTHS = 60


def check_category_distributions(transactions_path: str) -> list:
    df = pd.read_csv(transactions_path)
    base = df[~df["is_injected_anomaly"]]
    findings = []
    for category, (mu, sigma) in CATEGORY_LOGNORMAL_PARAMS.items():
        target_mean = np.exp(mu + sigma ** 2 / 2)
        target_median = np.exp(mu)
        target_std = np.sqrt((np.exp(sigma ** 2) - 1) * np.exp(2 * mu + sigma ** 2))

        observed = base.loc[base["merchant_category"] == category, "amount_usd"]
        if observed.empty:
            findings.append((category, "mean", target_mean, None, None, True))
            continue

        obs_mean, obs_median, obs_std = observed.mean(), observed.median(), observed.std()
        for label, target, observed_val in [
            ("mean", target_mean, obs_mean),
            ("median", target_median, obs_median),
            ("std", target_std, obs_std),
        ]:
            pct_off = abs(observed_val - target) / target if target else float("inf")
            flagged = pct_off > DIST_FLAG_THRESHOLD
            findings.append((category, label, target, observed_val, pct_off, flagged))
    return findings


def check_concentration(transactions_path: str, employees_path: str) -> dict:
    df = pd.read_csv(transactions_path)
    employees = pd.read_csv(employees_path)
    df = df.merge(employees[["employee_id", "department"]], on="employee_id", how="left")

    n_hot_expected = max(1, round(len(employees) * HOT_EMPLOYEE_FRACTION))
    anomalies = df[df["is_injected_anomaly"]]
    per_employee_anomaly_counts = anomalies.groupby("employee_id").size().sort_values(ascending=False)
    top_hot_share = (
        per_employee_anomaly_counts.head(n_hot_expected).sum() / len(anomalies) if len(anomalies) else 0.0
    )

    dept_dummies = pd.get_dummies(df["department"], prefix="dept")
    corr_frame = pd.concat([dept_dummies, df["is_injected_anomaly"].astype(int)], axis=1)
    dept_corr = corr_frame.corr()["is_injected_anomaly"].drop("is_injected_anomaly")

    unintended = {k: v for k, v in dept_corr.items() if abs(v) > CORR_FLAG_THRESHOLD}

    return {
        "expected_hot_share": HOT_ANOMALY_SHARE,
        "observed_top_decile_anomaly_share": round(float(top_hot_share), 4),
        "department_correlation": dept_corr.round(4).to_dict(),
        "unintended_department_correlation": unintended,
    }


def check_duration_granularity(employees_path: str) -> dict:
    """Compare distinct duration_months values before (tenure_years * 12,
    the coarse annual-only approach previously used, kept here only for
    comparison — no longer used downstream) vs. after (the fine-grained,
    timeline-anchored value actually generated — see
    assign_fine_grained_duration() in attrition_extension.py)."""
    df = pd.read_csv(employees_path)
    before = int((df["tenure_years"] * 12).nunique())
    after = int(df["duration_months"].nunique())
    return {
        "distinct_duration_before": before,
        "distinct_duration_after": after,
        "still_too_coarse": after < MIN_DISTINCT_DURATION_MONTHS,
    }


def perturbation_sensitivity(employees_path: str, rng_seed: int = 999) -> dict:
    employees = pd.read_csv(employees_path)
    rng = np.random.default_rng(rng_seed)

    perturbed_lambda = {k: v * float(rng.uniform(0.8, 1.2)) for k, v in DEPARTMENT_LAMBDA.items()}
    perturbed_lognormal = {
        k: (mu + np.log(float(rng.uniform(0.8, 1.2))), sigma * float(rng.uniform(0.8, 1.2)))
        for k, (mu, sigma) in CATEGORY_LOGNORMAL_PARAMS.items()
    }

    import src.generation.spend_generator as sg

    original_lambda, original_lognormal = dict(sg.DEPARTMENT_LAMBDA), dict(sg.CATEGORY_LOGNORMAL_PARAMS)
    try:
        sg.DEPARTMENT_LAMBDA.update(perturbed_lambda)
        sg.CATEGORY_LOGNORMAL_PARAMS.update(perturbed_lognormal)
        base_df = generate_base_transactions(employees, np.random.default_rng(rng_seed + 1))
        n_hot = max(1, round(len(employees) * HOT_EMPLOYEE_FRACTION))
        hot_employees = set(
            np.random.default_rng(rng_seed + 2)
            .choice(employees["employee_id"].values, size=n_hot, replace=False)
            .tolist()
        )
        perturbed_df = inject_anomalies(
            base_df, employees["employee_id"].tolist(), 0.05, hot_employees, np.random.default_rng(rng_seed + 3)
        )
    finally:
        sg.DEPARTMENT_LAMBDA.clear()
        sg.DEPARTMENT_LAMBDA.update(original_lambda)
        sg.CATEGORY_LOGNORMAL_PARAMS.clear()
        sg.CATEGORY_LOGNORMAL_PARAMS.update(original_lognormal)

    type_mix = perturbed_df.loc[perturbed_df["is_injected_anomaly"], "anomaly_type"].value_counts(normalize=True)
    category_medians = perturbed_df.loc[~perturbed_df["is_injected_anomaly"]].groupby("merchant_category")[
        "amount_usd"
    ].median()

    return {
        "perturbed_total_transactions": len(perturbed_df),
        "perturbed_anomaly_rate": round(float(perturbed_df["is_injected_anomaly"].mean()), 4),
        "perturbed_anomaly_type_mix": type_mix.round(3).to_dict(),
        "perturbed_category_medians": category_medians.round(2).to_dict(),
    }


def build_report(out_dir: str, employees_path: str, transactions_path: str) -> str:
    dist_findings = check_category_distributions(transactions_path)
    concentration = check_concentration(transactions_path, employees_path)
    perturbation = perturbation_sensitivity(employees_path)
    duration_granularity = check_duration_granularity(employees_path)

    lines = ["# Synthetic Data Validation Report", ""]

    lines.append("## 1. Per-category amount distribution vs. documented target parameters")
    lines.append("")
    lines.append("| category | stat | target | observed | % off | flagged (>15%) |")
    lines.append("|---|---|---|---|---|---|")
    any_dist_flag = False
    for category, label, target, observed, pct_off, flagged in dist_findings:
        any_dist_flag = any_dist_flag or flagged
        obs_str = f"{observed:.2f}" if observed is not None else "N/A"
        pct_str = f"{pct_off:.1%}" if pct_off is not None else "N/A"
        lines.append(f"| {category} | {label} | {target:.2f} | {obs_str} | {pct_str} | {'YES' if flagged else 'no'} |")
    lines.append("")
    lines.append(
        "No distribution flags raised."
        if not any_dist_flag
        else "**Flags raised above — see table.** Base (non-anomalous) transaction amounts "
        "deviate from the documented lognormal target parameters by more than 15% for the rows marked YES."
    )
    lines.append("")

    lines.append("## 2. Unintended correlation check (department / employee vs. is_injected_anomaly)")
    lines.append("")
    lines.append(
        f"- Designed concentration: {concentration['expected_hot_share']:.0%} of injected anomalies should land "
        f"among the top {HOT_EMPLOYEE_FRACTION:.0%} highest-anomaly-count employees (the deliberately designated "
        "'hot' group) — this concentration is intentional and expected."
    )
    lines.append(
        f"- Observed: top-decile-by-anomaly-count employees account for "
        f"{concentration['observed_top_decile_anomaly_share']:.1%} of all injected anomalies."
    )
    lines.append("- Department-level point-biserial correlation with is_injected_anomaly:")
    for dept, corr in concentration["department_correlation"].items():
        lines.append(f"  - {dept}: {corr:.3f}")
    if concentration["unintended_department_correlation"]:
        lines.append(
            "- **Unintended correlation flagged** (|corr| > 0.30, beyond the deliberate employee-level "
            f"concentration): {concentration['unintended_department_correlation']}"
        )
    else:
        lines.append("- No unintended department-level correlation above the 0.30 threshold.")
    lines.append("")

    lines.append("## 3. Generation-parameter perturbation sensitivity (+/-20%)")
    lines.append("")
    lines.append(
        "Department transaction-frequency lambdas and per-category lognormal (mu, sigma) parameters were each "
        "perturbed by a uniform random factor in [0.8, 1.2] and the full base + anomaly-injection generation was "
        "re-run independently of the primary dataset."
    )
    lines.append(f"- Perturbed run total transactions: {perturbation['perturbed_total_transactions']:,}")
    lines.append(f"- Perturbed run anomaly rate: {perturbation['perturbed_anomaly_rate']:.2%} (target 5%)")
    lines.append(f"- Perturbed run anomaly-type mix: {perturbation['perturbed_anomaly_type_mix']}")
    lines.append(f"- Perturbed run category medians: {perturbation['perturbed_category_medians']}")
    lines.append("")
    lines.append(
        "**Qualitative conclusion:** under a +/-20% perturbation of generation parameters, the anomaly rate "
        "stays at the ~5% target, the three anomaly types remain roughly evenly split, and category amount "
        "medians retain the same relative ordering (travel > client_entertainment > software_saas > other > "
        "office_supplies ~ meals) as the primary dataset. This is a data-level stability check only — see the "
        "module docstring above for why the model-eval-level version of this question is answered separately by "
        "the 1%/5%/10% injection-rate robustness comparison in src/models/spend/evaluate.py."
    )
    lines.append("")

    lines.append("## 4. Duration granularity (attrition survival target)")
    lines.append("")
    lines.append(
        "The real IBM dataset's YearsAtCompany is annual-resolution only. duration_months is a disclosed "
        "synthetic refinement (see assign_fine_grained_duration() in attrition_extension.py), anchored to each "
        "employee's own generated comp_history timeline rather than an independent random draw."
    )
    lines.append(
        f"- Distinct duration_months values, before (tenure_years * 12, no longer used downstream): "
        f"{duration_granularity['distinct_duration_before']}"
    )
    lines.append(
        f"- Distinct duration_months values, after (fine-grained, timeline-anchored): "
        f"{duration_granularity['distinct_duration_after']}"
    )
    if duration_granularity["still_too_coarse"]:
        lines.append(
            f"- **FLAGGED:** still under the {MIN_DISTINCT_DURATION_MONTHS}-distinct-value threshold "
            "considered meaningfully improved over the annual-only original."
        )
    else:
        lines.append(f"- Above the {MIN_DISTINCT_DURATION_MONTHS}-distinct-value threshold — not flagged.")
    lines.append("")

    report = "\n".join(lines)
    os.makedirs(out_dir, exist_ok=True)
    report_path = os.path.join(out_dir, "validation_report.md")
    with open(report_path, "w") as f:
        f.write(report)
    return report_path


if __name__ == "__main__":
    path = build_report(
        out_dir="data/generated",
        employees_path="data/generated/employees.csv",
        transactions_path="data/generated/expense_transactions_5pct.csv",
    )
    print(f"Validation report written to {path}")
